# Generated by Django 6.0.6 on 2026-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('long_url', models.TextField()),
                ('long_url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'url_mapping',
                'indexes': [models.Index(fields=['short_code'], name='url_mapping_short_c_e9218b_idx'), models.Index(fields=['long_url_hash'], name='url_mapping_long_ur_a123f8_idx')],
            },
        ),
    ]
