# Generated by Django 6.0.6 on 2026-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_remove_urlmapping_url_mapping_short_c_e9218b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=15)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'click_events',
                'indexes': [models.Index(fields=['short_code', 'clicked_at'], name='click_event_short_c_edd16e_idx')],
            },
        ),
    ]
