# Generated by Django 6.0.6 on 2026-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='urlmapping',
            name='url_mapping_short_c_e9218b_idx',
        ),
        migrations.RenameIndex(
            model_name='urlmapping',
            new_name='idx_long_url_hash',
            old_name='url_mapping_long_ur_a123f8_idx',
        ),
        migrations.AddIndex(
            model_name='urlmapping',
            index=models.Index(fields=['short_code', 'long_url'], name='idx_covering_redirect'),
        ),
    ]
